const $ = (s) => document.querySelector(s);
const els = {
  search: $("#search"), catSearch: $("#catSearch"), categoryList: $("#categoryList"), filterLine: $("#filterLine"),
  productGrid: $("#productGrid"), emptyProducts: $("#emptyProducts"), btnUseFolder: $("#btnUseFolder"),
  btnLoadJson: $("#btnLoadJson"), btnDownloadJson: $("#btnDownloadJson"), filePicker: $("#filePicker"),
  saveStatus: $("#saveStatus"), dataStatus: $("#dataStatus"), cartPanel: $("#cartPanel"), cartList: $("#cartList"),
  cartSummaryTop: $("#cartSummaryTop"), shipDate: $("#shipDate"), shipDestination: $("#shipDestination"),
  shipRecipient: $("#shipRecipient"), shipReference: $("#shipReference"), shipNotes: $("#shipNotes"),
  shipExtraUE: $("#shipExtraUE"), btnClearCart: $("#btnClearCart"), btnCreateShipment: $("#btnCreateShipment"),
  mobileCartFab: $("#mobileCartFab"), mobileCartCount: $("#mobileCartCount"), btnCloseCart: $("#btnCloseCart"),
  btnHistory: $("#btnHistory"), historyDlg: $("#historyDlg"), btnCloseHistory: $("#btnCloseHistory"),
  historySearch: $("#historySearch"), historyList: $("#historyList"), productTpl: $("#productTpl"), cartRowTpl: $("#cartRowTpl")
};
const LOCAL_KEY = "campionature_state_v2";
let fsFolderHandle = null;
let state = { version: 2, categories: [], products: [], shipments: [] };
let ui = { selectedCategoryId: "__all__", search: "", catSearch: "", editingShipmentId: null };
let shipmentCart = [];
let saveTimer = null;
function todayISO(){ return new Date().toISOString().slice(0,10); }
function uid(prefix="id"){ return `${prefix}_${Math.random().toString(36).slice(2,8)}_${Date.now().toString(36)}`; }
function n(v){ const x = Number(v); return Number.isFinite(x) ? x : 0; }
function escapeHtml(str){ return String(str ?? "").replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch])); }
function inferCustomsCode(product){ const catNames=(product.categoryIds||[]).map(id=>state.categories.find(c=>c.id===id)?.name||"").join(" ").toLowerCase(); const txt=`${product.name||""} ${catNames}`.toLowerCase(); if(txt.includes("wafer")) return "19053219"; if(txt.includes("biscotti")||txt.includes("biscuit")) return "19053119"; if(txt.includes("savoiardi")) return "19059080"; if(txt.includes("patatine")) return "20052020"; return "19059070"; }
function normalizeLots(lots){ if(!Array.isArray(lots)) return []; return lots.map(l=>({expiry:l?.expiry||"__unknown__", qty:Math.max(0,Math.trunc(n(l?.qty))), ordered:!!l?.ordered})).filter(l=>l.qty>0||l.ordered); }
function normalizeState(obj){ state=obj&&typeof obj==="object"?obj:{}; state.version=state.version||2; state.categories=Array.isArray(state.categories)?state.categories:[]; state.products=Array.isArray(state.products)?state.products:[]; state.shipments=Array.isArray(state.shipments)?state.shipments:[]; for(const c of state.categories){ c.id=c.id||uid("cat"); c.name=c.name||"Unnamed"; } for(const p of state.products){ p.id=p.id||uid("prod"); p.name=p.name||"Unnamed product"; p.categoryIds=Array.isArray(p.categoryIds)?p.categoryIds:[]; p.wordings=Array.isArray(p.wordings)?p.wordings:[]; p.codes=Array.isArray(p.codes)?p.codes:[]; p.notes=p.notes||""; p.imageFileName=p.imageFileName||""; p.ctSize=Math.max(1,Math.trunc(n(p.ctSize)||1)); p.customsCode=p.customsCode||inferCustomsCode(p); p.unitWeightKg=p.unitWeightKg||""; p.lots=normalizeLots(p.lots);} for(const s of state.shipments){ s.id=s.id||uid("ship"); s.code=s.code||buildShipmentCode(s.date||todayISO()); s.date=s.date||todayISO(); s.destination=s.destination||""; s.recipient=s.recipient||""; s.reference=s.reference||""; s.notes=s.notes||""; s.extraUE=!!s.extraUE; s.createdAt=s.createdAt||new Date().toISOString(); s.items=Array.isArray(s.items)?s.items.map(it=>({productId:it.productId||"", productName:it.productName||"", lotExpiry:it.lotExpiry||"__unknown__", unitMode:it.unitMode==="ct"?"ct":"units", qty:Math.max(1,Math.trunc(n(it.qty)||1)), qtyUnits:Math.max(1,Math.trunc(n(it.qtyUnits||it.qty)||1)), ctSize:Math.max(1,Math.trunc(n(it.ctSize)||1)), customsCode:it.customsCode||"", unitWeightKg:it.unitWeightKg||""})):[]; } writeShipmentForm({date:todayISO()}); }
function categoryLabel(product){ const names=(product.categoryIds||[]).map(id=>state.categories.find(c=>c.id===id)?.name).filter(Boolean); return names.join(", ")||"No category"; }
function productImagePath(product){ return product.imageFileName?`media/${product.imageFileName}`:""; }
function availableLots(product){ return normalizeLots(product.lots).filter(l=>!l.ordered&&l.qty>0).sort((a,b)=>{ const aa=a.expiry==="__unknown__"?"9999-12-31":a.expiry; const bb=b.expiry==="__unknown__"?"9999-12-31":b.expiry; return aa.localeCompare(bb);}); }
function totalStock(product){ return availableLots(product).reduce((sum,lot)=>sum+lot.qty,0); }
function formatDateISO(iso){ if(!iso||iso==="__unknown__") return "Unknown"; const [y,m,d]=iso.split("-"); return `${d}/${m}/${y}`; }
function buildShipmentCode(date){ const ymd=(date||todayISO()).replaceAll("-",""); const idx=(state.shipments||[]).filter(s=>(s.date||"")=== (date||todayISO())).length+1; return `SHP-${ymd}-${String(idx).padStart(3,"0")}`; }
function filteredProducts(){ return state.products.filter(p=>{ if(ui.selectedCategoryId!=="__all__" && !(p.categoryIds||[]).includes(ui.selectedCategoryId)) return false; if(!ui.search) return true; const hay=[p.name,...(p.wordings||[]),...(p.codes||[]),p.notes].join(" ").toLowerCase(); return hay.includes(ui.search);}); }
function renderCategories(){ const rows=state.categories.filter(c=>!ui.catSearch||(c.name||"").toLowerCase().includes(ui.catSearch)).sort((a,b)=>(a.name||"").localeCompare(b.name||"")); els.categoryList.innerHTML=""; const all=[{id:"__all__",name:"All"},...rows]; for(const cat of all){ const count=cat.id==="__all__"?state.products.length:state.products.filter(p=>(p.categoryIds||[]).includes(cat.id)).length; const div=document.createElement("div"); div.className="catItem"+(ui.selectedCategoryId===cat.id?" active":""); div.innerHTML=`<span>${escapeHtml(cat.name)}</span><span class="smallNote">${count}</span>`; div.onclick=()=>{ ui.selectedCategoryId=cat.id; renderCategories(); renderProducts();}; els.categoryList.appendChild(div);} }
function renderProducts(){ const rows=filteredProducts(); els.productGrid.innerHTML=""; els.emptyProducts.hidden=rows.length>0; const catTxt=ui.selectedCategoryId==="__all__"?"All categories":(state.categories.find(c=>c.id===ui.selectedCategoryId)?.name||""); els.filterLine.textContent=`${rows.length} prodotti • ${catTxt}`; for(const p of rows){ const node=els.productTpl.content.cloneNode(true); node.querySelector(".cardName").textContent=p.name; node.querySelector(".cardCat").textContent=categoryLabel(p); node.querySelector(".stockPill").textContent=`Stock ${totalStock(p)} units`; node.querySelector(".ctPill").textContent=`CT ${p.ctSize}`; node.querySelector(".codesLine").textContent=(p.codes||[]).slice(0,1).join(", "); const img=node.querySelector(".thumbImg"); const empty=node.querySelector(".thumbEmpty"); const src=productImagePath(p); if(src){ img.src=src; img.style.display=""; empty.hidden=true; img.onerror=()=>{ img.style.display="none"; empty.hidden=false; }; } node.querySelector(".addBtn").onclick=()=>addToCart(p.id); els.productGrid.appendChild(node);} }
function cartDetails(row){ const product=state.products.find(p=>p.id===row.productId); if(!product) return null; const lots=availableLots(product); const selectedLot=lots.find(l=>l.expiry===row.lotExpiry)||lots[0]||null; const unitMode=row.unitMode==="ct"?"ct":"units"; const qty=Math.max(1,Math.trunc(n(row.qty)||1)); const ctSize=Math.max(1,product.ctSize||1); const requestedUnits=unitMode==="ct"?qty*ctSize:qty; const availableUnits=selectedLot?selectedLot.qty:0; const availableMode=unitMode==="ct"?Math.floor(availableUnits/ctSize):availableUnits; const totalWeight=product.unitWeightKg?(n(product.unitWeightKg)*requestedUnits):0; return {product,lots,selectedLot,unitMode,qty,ctSize,requestedUnits,availableUnits,availableMode,totalWeight}; }
function addToCart(productId){ const p=state.products.find(x=>x.id===productId); if(!p) return; const lots=availableLots(p); if(!lots.length){ alert("Nessun lotto disponibile per questo prodotto."); return; } shipmentCart.push({productId, lotExpiry:lots[0].expiry, unitMode:"units", qty:1}); renderCart(); openCartMobile(); }
function renderCart(){ els.cartList.innerHTML=""; const totalLines=shipmentCart.length; const totalUnits=shipmentCart.reduce((sum,row)=>{ const d=cartDetails(row); return sum+(d?d.requestedUnits:0);},0); els.cartSummaryTop.textContent=totalLines?`${totalLines} righe • ${totalUnits} unità`:"Nessun prodotto selezionato"; els.mobileCartCount.textContent=String(totalLines); if(!shipmentCart.length){ const div=document.createElement("div"); div.className="empty"; div.textContent="Aggiungi uno o più prodotti al carrello."; els.cartList.appendChild(div); return; } shipmentCart.forEach((row,idx)=>{ const d=cartDetails(row); if(!d) return; const node=els.cartRowTpl.content.cloneNode(true); node.querySelector(".cartRowName").textContent=d.product.name; node.querySelector(".cartRowSub").textContent=`${categoryLabel(d.product)} • Doganale ${d.product.customsCode||"-"}`; const lotSel=node.querySelector(".lotSel"); d.lots.forEach(lot=>{ const opt=document.createElement("option"); opt.value=lot.expiry; opt.textContent=`${formatDateISO(lot.expiry)} • ${lot.qty} units`; if(lot.expiry===d.selectedLot?.expiry) opt.selected=true; lotSel.appendChild(opt);}); lotSel.onchange=()=>{ shipmentCart[idx].lotExpiry=lotSel.value; scheduleSave(); renderCart();}; const modeSel=node.querySelector(".modeSel"); modeSel.value=d.unitMode; modeSel.onchange=()=>{ shipmentCart[idx].unitMode=modeSel.value; scheduleSave(); renderCart();}; const qtyInput=node.querySelector(".qtyInput"); qtyInput.value=d.qty; qtyInput.onchange=()=>{ shipmentCart[idx].qty=Math.max(1,parseInt(qtyInput.value||"1",10)||1); scheduleSave(); renderCart();}; node.querySelector(".removeBtn").onclick=()=>{ shipmentCart.splice(idx,1); scheduleSave(); renderCart();}; node.querySelector(".stepMinus").onclick=()=>{ shipmentCart[idx].qty=Math.max(1,(shipmentCart[idx].qty||1)-1); scheduleSave(); renderCart();}; node.querySelector(".stepPlus").onclick=()=>{ shipmentCart[idx].qty=Math.max(1,(shipmentCart[idx].qty||1)+1); scheduleSave(); renderCart();}; const reqTxt=d.unitMode==="ct"?`${d.qty} CT = ${d.requestedUnits} units`:`${d.qty} units`; const availTxt=d.unitMode==="ct"?`${d.availableMode} CT disponibili`:`${d.availableMode} unità disponibili`; const weightTxt=d.totalWeight?` • ${d.totalWeight.toFixed(2)} kg`:""; node.querySelector(".availability").textContent=`Lotto ${formatDateISO(d.selectedLot?.expiry)} • ${availTxt} • ${reqTxt}${weightTxt}`; els.cartList.appendChild(node);}); }
function readShipmentForm(){ return { date:els.shipDate.value||todayISO(), destination:(els.shipDestination.value||"").trim(), recipient:(els.shipRecipient.value||"").trim(), reference:(els.shipReference.value||"").trim(), notes:(els.shipNotes.value||"").trim(), extraUE:!!els.shipExtraUE.checked }; }
function writeShipmentForm(v){ els.shipDate.value=v?.date||todayISO(); els.shipDestination.value=v?.destination||""; els.shipRecipient.value=v?.recipient||""; els.shipReference.value=v?.reference||""; els.shipNotes.value=v?.notes||""; els.shipExtraUE.checked=!!v?.extraUE; }
function validateCart(){ if(!shipmentCart.length){ alert("Aggiungi almeno un prodotto."); return false; } for(const row of shipmentCart){ const d=cartDetails(row); if(!d||!d.selectedLot){ alert("Ogni riga deve avere un lotto valido."); return false; } if(d.requestedUnits>d.availableUnits){ alert(`${d.product.name}: il lotto ${formatDateISO(d.selectedLot.expiry)} ha solo ${d.availableUnits} unità disponibili.`); return false; } } return true; }
function consumeLot(productId,expiry,qtyUnits){ const p=state.products.find(x=>x.id===productId); if(!p) return false; const lot=(p.lots||[]).find(l=>!l.ordered&&l.expiry===expiry); if(!lot||lot.qty<qtyUnits) return false; lot.qty-=qtyUnits; p.lots=normalizeLots(p.lots); return true; }
function restoreShipmentToStock(shipment){ (shipment.items||[]).forEach(it=>{ const p=state.products.find(x=>x.id===it.productId); if(!p) return; let lot=(p.lots||[]).find(l=>!l.ordered&&l.expiry===it.lotExpiry); if(!lot){ lot={expiry:it.lotExpiry||"__unknown__", qty:0, ordered:false}; p.lots.push(lot);} lot.qty+=it.qtyUnits; p.lots=normalizeLots(p.lots); }); }
async function createShipment(){ if(!validateCart()) return; const meta=readShipmentForm(); const shipment={ id:ui.editingShipmentId||uid("ship"), code:buildShipmentCode(meta.date), date:meta.date, destination:meta.destination, recipient:meta.recipient, reference:meta.reference, notes:meta.notes, extraUE:meta.extraUE, createdAt:new Date().toISOString(), items:shipmentCart.map(row=>{ const d=cartDetails(row); return {productId:d.product.id, productName:d.product.name, lotExpiry:d.selectedLot.expiry, unitMode:d.unitMode, qty:d.qty, qtyUnits:d.requestedUnits, ctSize:d.ctSize, customsCode:d.product.customsCode||"", unitWeightKg:d.product.unitWeightKg||""}; })}; for(const item of shipment.items){ if(!consumeLot(item.productId,item.lotExpiry,item.qtyUnits)){ alert(`Errore stock su ${item.productName}.`); return; } } state.shipments.unshift(shipment); shipmentCart=[]; ui.editingShipmentId=null; writeShipmentForm({date:todayISO()}); await persistStateNow(); renderProducts(); renderCart(); renderHistory(); exportShipmentPDF(shipment); if(shipment.extraUE) exportShipmentDHL(shipment); alert("Spedizione salvata."); closeCartMobile(); }
function filteredHistory(){ const q=(els.historySearch.value||"").trim().toLowerCase(); const rows=[...state.shipments].sort((a,b)=>`${b.date}|${b.createdAt}`.localeCompare(`${a.date}|${a.createdAt}`)); if(!q) return rows; return rows.filter(s=>{ const items=(s.items||[]).map(it=>`${it.productName} ${it.lotExpiry}`).join(" "); return [s.code,s.destination,s.recipient,s.reference,s.notes,items].join(" ").toLowerCase().includes(q); }); }
function renderHistory(){ if(!els.historyList) return; const rows=filteredHistory(); els.historyList.innerHTML=""; if(!rows.length){ const div=document.createElement("div"); div.className="empty"; div.textContent="Nessuna spedizione registrata."; els.historyList.appendChild(div); return; } rows.forEach(s=>{ const card=document.createElement("div"); card.className="histCard"; const itemsHtml=(s.items||[]).map(it=>{ const qtyTxt=it.unitMode==="ct"?`${it.qty} CT (${it.qtyUnits} units)`:`${it.qty} units`; return `<div class="histItem"><b>${escapeHtml(it.productName)}</b> • Lotto ${escapeHtml(formatDateISO(it.lotExpiry))} • ${escapeHtml(qtyTxt)}</div>`; }).join(""); card.innerHTML=`<div class="histTop"><div><div class="histCode">${escapeHtml(s.code||s.id)}</div><div class="histMeta">${escapeHtml(formatDateISO(s.date))} • ${escapeHtml(s.destination||"-")} • ${escapeHtml(s.reference||"-")}</div></div><div class="smallNote">${s.extraUE?"Extra UE":""}</div></div><div class="histItems">${itemsHtml}</div><div class="histActions"><button class="btn small editBtn" type="button">Modifica</button><button class="btn small ghost pdfBtn" type="button">PDF</button><button class="btn small ghost dhlBtn" type="button">DHL</button></div>`; card.querySelector(".editBtn").onclick=()=>editShipment(s.id); card.querySelector(".pdfBtn").onclick=()=>exportShipmentPDF(s); card.querySelector(".dhlBtn").onclick=()=>exportShipmentDHL(s); els.historyList.appendChild(card); }); }
async function editShipment(id){ const s=state.shipments.find(x=>x.id===id); if(!s) return; if(!confirm("Caricare questa spedizione nel carrello per modificarla?")) return; restoreShipmentToStock(s); state.shipments=state.shipments.filter(x=>x.id!==id); ui.editingShipmentId=s.id; shipmentCart=(s.items||[]).map(it=>({productId:it.productId, lotExpiry:it.lotExpiry, unitMode:it.unitMode==="ct"?"ct":"units", qty:it.qty})); writeShipmentForm(s); await persistStateNow(); renderProducts(); renderCart(); renderHistory(); els.historyDlg.close(); openCartMobile(); window.scrollTo({top:0,behavior:"smooth"}); }
function exportShipmentDHL(shipment){ const lines=[]; (shipment.items||[]).forEach(it=>{ lines.push(it.customsCode||""); lines.push(`BALCONI [${it.productName}]`); lines.push(`[${it.unitWeightKg||""}]`); lines.push(""); }); const blob=new Blob([lines.join("\n")],{type:"text/plain;charset=utf-8"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=`${(shipment.code||"shipment").replace(/[^\w-]+/g,"_")}_DHL.txt`; a.click(); URL.revokeObjectURL(a.href); }
function exportShipmentPDF(shipment){ const items=(shipment.items||[]).map(it=>{ const qtyTxt=it.unitMode==="ct"?`${it.qty} CT (${it.qtyUnits} units)`:`${it.qty} units`; return `<tr><td>${escapeHtml(it.productName)}</td><td>${escapeHtml(formatDateISO(it.lotExpiry))}</td><td>${escapeHtml(qtyTxt)}</td><td>${escapeHtml(it.customsCode||"")}</td></tr>`; }).join(""); const html=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(shipment.code||shipment.id)}</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}h1{font-size:22px;margin:0 0 10px}.meta{font-size:13px;color:#444;margin-bottom:16px;line-height:1.5}table{width:100%;border-collapse:collapse}th,td{border:1px solid #d9d9d9;padding:8px;text-align:left;font-size:13px}th{background:#f3f3f3}</style></head><body><h1>Shipment ${escapeHtml(shipment.code||shipment.id)}</h1><div class="meta">Date: ${escapeHtml(formatDateISO(shipment.date))}<br>Destination: ${escapeHtml(shipment.destination||"-")}<br>Recipient: ${escapeHtml(shipment.recipient||"-")}<br>Reference: ${escapeHtml(shipment.reference||"-")}<br>Notes: ${escapeHtml(shipment.notes||"-")}<br>Extra UE: ${shipment.extraUE?"Yes":"No"}</div><table><thead><tr><th>Product</th><th>Lot</th><th>Qty</th><th>Customs</th></tr></thead><tbody>${items}</tbody></table><script>window.onload=()=>window.print();</script></body></html>`; const w=window.open("","_blank"); if(!w){ alert("Popup bloccato dal browser."); return; } w.document.open(); w.document.write(html); w.document.close(); }
function exportJsonDownload(){ const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="catalogue.json"; a.click(); URL.revokeObjectURL(a.href); }
function openCartMobile(){ if(window.innerWidth<=980) els.cartPanel.classList.add("open"); }
function closeCartMobile(){ if(window.innerWidth<=980) els.cartPanel.classList.remove("open"); }
async function loadFromDefaultCatalogue(){ try{ const res=await fetch("catalogue.json",{cache:"no-store"}); const obj=await res.json(); normalizeState(obj); els.dataStatus.textContent="Dati caricati da catalogue.json"; }catch{ const fromLocal=localStorage.getItem(LOCAL_KEY); if(fromLocal){ normalizeState(JSON.parse(fromLocal)); els.dataStatus.textContent="Dati caricati da autosave locale"; } else { normalizeState({version:2,categories:[],products:[],shipments:[]}); els.dataStatus.textContent="Nessun dato trovato"; } } }
function saveLocalBackup(){ localStorage.setItem(LOCAL_KEY, JSON.stringify(state)); els.saveStatus.textContent="Salvato in autosave locale"; }
async function persistFolderJson(){ if(!fsFolderHandle) return false; const fileHandle=await fsFolderHandle.getFileHandle("catalogue.json",{create:true}); const writable=await fileHandle.createWritable(); await writable.write(JSON.stringify(state,null,2)); await writable.close(); els.dataStatus.textContent="Salvato in catalogue.json (folder mode)"; return true; }
function scheduleSave(){ saveLocalBackup(); clearTimeout(saveTimer); saveTimer=setTimeout(()=>{ persistStateNow(); },400); }
async function persistStateNow(){ saveLocalBackup(); if(fsFolderHandle){ try{ await persistFolderJson(); els.saveStatus.textContent="Autosave cartella attivo"; }catch{ els.saveStatus.textContent="Errore autosave cartella, backup locale salvato"; } } }
async function chooseFolderAutosave(){ if(!window.showDirectoryPicker){ alert("Folder autosave disponibile solo in Chrome/Edge desktop."); return; } try{ const dir=await window.showDirectoryPicker({mode:"readwrite"}); fsFolderHandle=dir; try{ const fileHandle=await dir.getFileHandle("catalogue.json",{create:false}); const file=await fileHandle.getFile(); const text=await file.text(); normalizeState(JSON.parse(text)); els.dataStatus.textContent="Dati caricati dalla cartella selezionata"; renderAll(); }catch{ await persistFolderJson(); } els.saveStatus.textContent="Autosave cartella attivo"; }catch{} }
async function loadJsonFromPicker(ev){ const file=ev.target.files?.[0]; if(!file) return; const text=await file.text(); normalizeState(JSON.parse(text)); renderAll(); await persistStateNow(); els.dataStatus.textContent=`Dati caricati da ${file.name}`; ev.target.value=""; }
function renderAll(){ renderCategories(); renderProducts(); renderCart(); renderHistory(); }
function bind(){ els.search.addEventListener("input",()=>{ ui.search=(els.search.value||"").trim().toLowerCase(); renderProducts(); }); els.catSearch.addEventListener("input",()=>{ ui.catSearch=(els.catSearch.value||"").trim().toLowerCase(); renderCategories(); }); [els.shipDate,els.shipDestination,els.shipRecipient,els.shipReference,els.shipNotes,els.shipExtraUE].forEach(el=>{ el.addEventListener("input",scheduleSave); el.addEventListener("change",scheduleSave); }); els.btnUseFolder.onclick=chooseFolderAutosave; els.btnLoadJson.onclick=()=>els.filePicker.click(); els.filePicker.onchange=loadJsonFromPicker; els.btnDownloadJson.onclick=exportJsonDownload; els.btnClearCart.onclick=async()=>{ if(!shipmentCart.length) return; if(!confirm("Svuotare il carrello?")) return; shipmentCart=[]; ui.editingShipmentId=null; writeShipmentForm({date:todayISO()}); await persistStateNow(); renderCart(); }; els.btnCreateShipment.onclick=createShipment; els.mobileCartFab.onclick=openCartMobile; els.btnCloseCart.onclick=closeCartMobile; els.btnHistory.onclick=()=>{ renderHistory(); els.historyDlg.showModal(); }; els.btnCloseHistory.onclick=()=>els.historyDlg.close(); els.historySearch.oninput=renderHistory; window.addEventListener("beforeunload",()=>{ saveLocalBackup(); }); }
(async function init(){ bind(); await loadFromDefaultCatalogue(); renderAll(); })();